### ISSUE TITLE
ID head loss vs batch_size

### ISSUE THREAD

**Issue by haribaskarsony** [ml-jku/MIM-Refiner#10]
Hi, with refernec e to the previous discussion: https://github.com/ml-jku/MIM-Refiner/issues/9#issuecomment-2343692994
I refined my model with a batch_size=512. This is the comparison of the stage 2 loss curves for batch_size:16 and batch_size:512.

batchsize_16, temperature_0.2
![image](https://github.com/user-attachments/assets/8d7671ae-cdae-4279-8b9e-bf0e8807e005)

batchsize_512, temperature_0.2
![image](https://github.com/user-attachments/assets/16e3cd28-c5f1-4592-b1cf-1a43c6af62cc)

Is this an expected behavior? the range of loss values are different and batch_512 model could not reach the lowest loss achieved by batch_16 model.

**Comment by BenediktAlkin** [comment]
Loss is not indicative of representation quality. Its obviously easier to find the positive in 16 samples than it is in 512 samples. So yes, this is expected. If the dataset allows it, you should look at something like k-NN accuracy somewhere in the head.

**Comment by haribaskarsony** [comment]
Out of the context, where is the code for NNA objective equation implemented in the repo?
![image](https://github.com/user-attachments/assets/7ba60d3c-c24b-4ba2-977e-dabdb3296696)

**Comment by BenediktAlkin** [comment]
The loss is implemented [here](https://github.com/ml-jku/MIM-Refiner/blob/cc574235995e2115909a6fb91b91ff703af744c2/src/losses/ssl/nnclr_loss.py#L90) and the NN swap [here](https://github.com/ml-jku/MIM-Refiner/blob/cc574235995e2115909a6fb91b91ff703af744c2/src/modules/ssl/nnclr_queue.py#L125).
