### ISSUE TITLE
use of no_aug_train set

### ISSUE THREAD

**Issue by haribaskarsony** [ml-jku/MIM-Refiner#5]
Hi what is the use of no_aug_train_10p set ?
When i tried to refine with imagenet, it eexpected a no_aug train set. What is its purpose?

**Comment by BenediktAlkin** [comment]
Hi, the purpose is to get a metric of representation quality already during training.
We use 10% of imagenet (the imagenet1k_10percent_simclrv2 dataset is a subset of ImageNet containing only 10% that was also used in SimCLRv2) to train a k-NN classifier.

We find this to provide a relatively good proxy for downstream performance during training.
"Noaug" indicates that no augmentations are applied, as the k-NN classifier is typically trained on non-augmented images.

You can create the dataset with [this](https://github.com/BenediktAlkin/ImageNetSubsetGenerator) repo, or you can simply remove the "train_noaug_10p" dataset from the yaml and then also remove the "offline_knn_metrics_callback".

[Appendix G](https://arxiv.org/pdf/2402.10093) contains some additional information.


As an example: for MAE-Refined-L/16 the k-NN accuracy trained on the 10% subset looks like this:
![image](https://github.com/user-attachments/assets/93334a87-bcb4-45f0-b170-6184ffb26f73)

When you have bad hyperparameters (e.g. LR is too large), the model will collapse and you immediately see it on the k-NN accuracy plot. When you try out hyperparameters, you can also compare the 10% k-NN directly and get a relatively good comparision of different hyperparameters.
