### ISSUE TITLE
model initializer code

### ISSUE THREAD

**Issue by haribaskarsony** [ml-jku/MIM-Refiner#7]
Hi @BenediktAlkin thank you for the reply.
I encountered a different issue while loading my model for refining.
It seems that i need to modify the model backbone structure to load my model. Could you pls point me to the files where i can do this?

Reg_token is an additional layer just like cls_token. 
I need to explicitly mention the dimension of reg_token layer to initialize and load my model weights.

_Originally posted by @haribaskarsony in https://github.com/ml-jku/MIM-Refiner/issues/6#issuecomment-2259735146_

**Comment by BenediktAlkin** [comment]
answered in original issue
